name: Auto Label PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Detect commit type
        id: detect
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MSG"

          if echo "$COMMIT_MSG" | grep -iE "^feat|^feature"; then
            echo "type=feature" >> "$GITHUB_OUTPUT"
          elif echo "$COMMIT_MSG" | grep -iE "^fix|^bug"; then
            echo "type=bug" >> "$GITHUB_OUTPUT"
          else
            echo "type=none" >> "$GITHUB_OUTPUT"

      - name: Add label to PR
        if: steps.detect.outputs.type != 'none'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ steps.detect.outputs.type }}
